// English translations. Keys are the Italian phrases used in the app.
import { registerEnglish } from './i18n.js';

registerEnglish({
  "Luci notturne: NASA Black Marble (GIBS)": "Night lights: NASA Black Marble (GIBS)",
  "Il volo è uscito dalla zona coperta dai ricevitori, oppure è atterrato. Sei di nuovo a terra.": "The flight has left receiver coverage or has landed. You're back on the ground.",
  "Aereo in volo": "Aircraft in flight",
  "Quota": "Altitude",
  "Velocità": "Speed",
  "Direzione": "Heading",
  "verso {dir}": "heading {dir}",
  "in direzione {dir}": "towards the {dir}",
  "Distanza da te": "Distance from you",
  "Decollo (stima)": "Take-off (estimate)",
  "verso le {time}": "around {time}",
  "Atterraggio (stima)": "Landing (estimate)",
  "Percorso": "Progress",
  "{pct}%, mancano {km} km": "{pct}%, {km} km to go",
  "Rotta non trasmessa da questo aereo": "This aircraft isn't broadcasting its route",
  "Cerco da dove viene e dove va…": "Looking up where it's from and where it's going…",
  "Rotta non disponibile per questo volo": "Route not available for this flight",
  "Codice radio": "Callsign",
  "Registrazione": "Registration",
  "{kn} nodi ({kmh} km/h)": "{kn} knots ({kmh} km/h)",
  "ferma": "stationary",
  "Verso {place}": "Bound for {place}",
  "Destinazione: {place}": "Destination: {place}",
  "Mancano": "Remaining",
  "{nm} miglia ({km} km in linea d'aria)": "{nm} nautical miles ({km} km as the crow flies)",
  "Arrivo (stima)": "Arrival (estimate)",
  "Destinazione scritta": "Destination as entered",
  "Destinazione non ancora ricevuta: le navi la trasmettono ogni 6 minuti. Lascia l'app aperta qualche minuto": "Destination not received yet: ships broadcast it every 6 minutes. Keep the app open for a few minutes",
  "Le piccole imbarcazioni (AIS classe B) non trasmettono destinazione né orari": "Small craft (AIS class B) don't broadcast a destination or arrival time",
  "Arrivo dichiarato": "Declared arrival",
  "Lunghezza": "Length",
  "Stazione spaziale con equipaggio": "Crewed space station",
  "Satellite in orbita": "Satellite in orbit",
  "{km} km in linea d'aria al suolo": "{km} km over the ground",
  "Suono": "Sound",
  "Muto": "Muted",
  ", atterraggio verso le {time}": ", landing around {time}",
  "A bordo di {name}": "On board {name}",
  "A bordo di {name}, {km} km di quota": "On board {name}, {km} km up",
  "Aerei non disponibili: il browser blocca le fonti dirette. Configura il Worker gratuito in js/config.js (vedi README).": "Aircraft unavailable: the browser blocks direct sources. Set up the free proxy in js/config.js (see README).",
  "Il Worker degli aerei non risponde. Riprovo tra pochi secondi.": "The aircraft proxy isn't responding. Retrying in a few seconds.",
  ". Dati {src}, aggiornati {age} s fa": ". Data from {src}, updated {age} s ago",
  ". Satelliti non disponibili ora": ". Satellites unavailable right now",
  "1 aereo e {sats} satelliti tracciati": "1 aircraft and {sats} satellites tracked",
  "{n} aerei e {sats} satelliti tracciati": "{n} aircraft and {sats} satellites tracked",
  "1 nave sul mare": "1 ship at sea",
  "{n} navi sul mare": "{n} ships at sea",
  "Navi non disponibili ora, riprovo tra 30 secondi": "Ships unavailable right now, retrying in 30 seconds",
  "Navi in arrivo…": "Ships on their way…",
  "Nessuna nave ricevuta finora: in questa zona i ricevitori AIS sono pochi, continuo ad ascoltare": "No ships received yet: there are few AIS receivers in this area, still listening",
  "Preparo il cielo sopra di te…": "Getting the sky above you ready…",
  "Questo browser non condivide la posizione. Cerca un luogo per nome.": "This browser doesn't share your location. Search for a place by name.",
  "Chiedo la posizione al browser…": "Asking the browser for your location…",
  "Posizione non disponibile. Cerca un luogo per nome.": "Location unavailable. Search for a place by name.",
  "Cerco…": "Searching…",
  "Nessun luogo con questo nome. Prova con la città più vicina.": "No place with that name. Try the nearest town.",
  "La ricerca non risponde. Controlla la connessione e riprova.": "Search isn't responding. Check your connection and try again.",
  "Torna dove eri": "Back to where you were",
  "Torna a {place}": "Back to {place}",
  "Versione {v}.": "Version {v}.",
  "Cerco nel cielo…": "Searching the sky…",
  "Nessun aereo in volo con questo codice. Forse non è ancora decollato o è già atterrato, oppure la compagnia usa via radio un codice diverso: prova quello che vedi sul tabellone o su un sito di voli.": "No aircraft in flight with that code. It may not have taken off yet or may have landed, or the airline uses a different radio callsign: try the one shown on the departures board or a flight-tracking site.",
  "L'ho trovato, ma in questo momento è a terra. Riprova quando sarà decollato.": "Found it, but it's on the ground right now. Try again once it has taken off.",
  "Sono al finestrino del volo {name} da {from} a {to}, a {alt} metri. Vieni a guardare in diretta:": "I'm at the window of flight {name} from {from} to {to}, {alt} metres up. Come and watch live:",
  "Sono al finestrino del volo {name}, a {alt} metri. Vieni a guardare in diretta:": "I'm at the window of flight {name}, {alt} metres up. Come and watch live:",
  ", a {km} km dalla Terra": ", {km} km above Earth",
  "Sono a bordo di {name}{alt}. Vieni a guardare in diretta:": "I'm on board {name}{alt}. Come and watch live:",
  "Link copiato: incollalo in un messaggio.": "Link copied: paste it into a message.",
  "Copia questo link:": "Copy this link:",
  "Non trovo più questo satellite. Guarda il cielo sopra di te.": "Can't find this satellite any more. Here's the sky above you.",
  "Cerco il volo…": "Looking for the flight…",
  "Questo volo non è più in aria: probabilmente è atterrato. Puoi guardare il cielo sopra di te.": "This flight is no longer in the air: it has probably landed. You can watch the sky above you instead.",
  "Preparo il viaggio in orbita…": "Preparing your trip to orbit…",
  "Ti hanno invitato al finestrino del volo {name}, in diretta. Tocca il pulsante e sali a bordo.": "You've been invited to the window seat of flight {name}, live. Tap the button to board.",
  "Ti hanno invitato a bordo di un satellite, in diretta. Tocca il pulsante e parti.": "You've been invited aboard a satellite, live. Tap the button to launch.",
  "quasi sopra la testa": "almost overhead",
  "alto nel cielo": "high in the sky",
  "a metà cielo": "halfway up the sky",
  "basso sull'orizzonte": "low on the horizon",
  "In questo momento nessun aereo è sopra il tuo orizzonte. Riprova tra qualche minuto.": "No aircraft above your horizon right now. Try again in a few minutes.",
  "Sto ancora caricando le orbite dei satelliti. Riapri tra qualche secondo.": "Still loading satellite orbits. Reopen in a few seconds.",
  "Nessun passaggio visibile nelle prossime 72 ore: in questi giorni la Stazione passa di giorno o in pieno buio, quando non è illuminata dal Sole.": "No visible passes in the next 72 hours: these days the Station passes in daylight or in full darkness, when it isn't lit by the Sun.",
  "Appare a {a} alle {t1}, sale fino a {el}° verso {b} e sparisce a {c} alle {t2}. Visibile a occhio nudo come un punto luminoso che si muove veloce, senza lampeggiare.": "Appears in the {a} at {t1}, climbs to {el}° in the {b} and disappears in the {c} at {t2}. Visible to the naked eye as a bright, fast-moving dot that doesn't blink.",
  "alle {time}": "at {time}",
  "per {min} min": "for {min} min",
  "Da {a} a {b}, alta fino a {el}° sull'orizzonte.": "From {a} to {b}, up to {el}° above the horizon.",
  "Aggiungi al calendario": "Add to calendar",
  "Stazione Spaziale Internazionale": "International Space Station",
  "Dove guardare": "Where to look",
  "Guarda a {dir}, basso sull'orizzonte: alle {time} la Stazione apparirà lì.": "Look {dir}, low on the horizon: at {time} the Station will appear there.",
  "Nave passeggeri o traghetto": "Passenger ship or ferry",
  "Nave da carico": "Cargo ship",
  "Petroliera o cisterna": "Tanker",
  "Mezzo veloce": "High-speed craft",
  "Aliscafo o ala marina": "Hydrofoil or wing-in-ground craft",
  "Imbarcazione": "Vessel",
  "Peschereccio": "Fishing vessel",
  "Rimorchiatore": "Tug",
  "Draga": "Dredger",
  "Supporto immersioni": "Diving support vessel",
  "Nave militare": "Military vessel",
  "Barca a vela": "Sailing boat",
  "Imbarcazione da diporto": "Pleasure craft",
  "Pilotina": "Pilot boat",
  "Soccorso in mare": "Search and rescue",
  "Nave di servizio portuale": "Port tender",
  "Mezzo antinquinamento": "Anti-pollution vessel",
  "Forze dell'ordine": "Law enforcement",
  "Mezzo sanitario": "Medical transport",
  "in navigazione a motore": "under way using engine",
  "all'ancora": "at anchor",
  "senza governo": "not under command",
  "manovra limitata": "restricted manoeuvrability",
  "ormeggiata": "moored",
  "in pesca": "fishing",
  "in navigazione a vela": "under way sailing",
  "Stazione spaziale cinese Tiangong": "Tiangong Chinese space station",
  "Passaggio visibile: {name}": "Visible pass: {name}",
  "Tra 10 minuti passa {name}": "{name} passes over in 10 minutes",
  "passaggio-stazione-spaziale.ics": "space-station-pass.ics",
  "È uscita una nuova versione di Finestrino. Aggiorno…": "A new version of Finestrino is out. Updating…",
  "sereno": "clear",
  "quasi sereno": "mostly clear",
  "poco nuvoloso": "partly cloudy",
  "coperto": "overcast",
  "nebbia": "fog",
  "nebbia gelata": "freezing fog",
  "pioviggine": "drizzle",
  "pioviggine fitta": "heavy drizzle",
  "pioggia debole": "light rain",
  "pioggia": "rain",
  "pioggia forte": "heavy rain",
  "pioggia gelata": "freezing rain",
  "neve debole": "light snow",
  "neve": "snow",
  "neve forte": "heavy snow",
  "nevischio": "snow grains",
  "rovesci": "showers",
  "rovesci forti": "heavy showers",
  "neve a rovesci": "snow showers",
  "temporale": "thunderstorm",
  "temporale con grandine": "thunderstorm with hail",
  "La tua posizione": "Your location",
  "Sotto il volo": "Below the flight",
  "Italia": "Italy",
  "Il cielo sopra di te, adesso. Scegli un aereo o un satellite che ti passa sopra e siediti al suo finestrino.": "The sky above you, right now. Pick a plane or satellite passing overhead and take its window seat.",
  "Sali a bordo": "Board",
  "Usa la mia posizione": "Use my location",
  "Cerca un luogo": "Search for a place",
  "Condividi": "Share",
  "Dal basso": "From below",
  "Dall'alto": "From above",
  "Sopra di me": "Above me",
  "Sinistra": "Left",
  "Avanti": "Ahead",
  "Destra": "Right",
  "Scendi": "Get off",
  "Da dove guardi il cielo?": "Where are you watching the sky from?",
  "Annulla": "Cancel",
  "Cerca": "Search",
  "Sopra di te adesso": "Above you now",
  "Gli aerei più vicini sopra il tuo orizzonte. Tocca un volo per vedere dove guardare.": "The nearest aircraft above your horizon. Tap a flight to see where to look.",
  "Stazione Spaziale: prossimi passaggi visibili": "Space Station: next visible passes",
  "Momenti in cui la vedrai a occhio nudo dal luogo scelto, se il cielo è sereno.": "Times you'll see it with the naked eye from your chosen place, if the sky is clear.",
  "Chiudi": "Close",
  "Cerca un volo in aria": "Find a flight in the air",
  "Scrivi il numero del volo come sul biglietto. Alcune compagnie, come Ryanair ed easyJet, via radio usano un codice diverso: se non lo trovo, prova quello che vedi sul tabellone o su un sito di voli (per esempio RYR4KX).": "Type the flight number as it appears on the ticket. Some airlines, like Ryanair and easyJet, use a different radio callsign: if I can't find it, try the one on the departures board or a flight-tracking site (for example RYR4KX).",
  "Fonti dei dati": "Data sources",
  "Finestrino è gratuito e non usa servizi a pagamento. Questi sono i dati aperti che lo rendono possibile.": "Finestrino is free and uses no paid services. These are the open data sources that make it possible.",
  "Non usare Finestrino per navigare: le posizioni possono essere in ritardo o mancare.": "Don't use Finestrino for navigation: positions can be delayed or missing.",
  "Il rumore di cabina è generato dal vivo nel browser, senza file audio.": "The cabin sound is generated live in your browser, with no audio files.",
  "Attribuzioni della mappa": "Map attributions",
  "<strong>Aerei</strong>: <a href=\"https://adsb.lol\" target=\"_blank\" rel=\"noopener\">ADSB.lol</a> (dati con licenza ODbL) e, come riserva, <a href=\"https://adsb.fi\" target=\"_blank\" rel=\"noopener\">adsb.fi</a>. Raccolti da volontari con ricevitori ADS-B.": "<strong>Aircraft</strong>: <a href=\"https://adsb.lol\" target=\"_blank\" rel=\"noopener\">ADSB.lol</a> (ODbL-licensed data) with <a href=\"https://adsb.fi\" target=\"_blank\" rel=\"noopener\">adsb.fi</a> as a fallback. Collected by volunteers with ADS-B receivers.",
  "<strong>Rotte dei voli</strong>: <a href=\"https://www.adsbdb.com\" target=\"_blank\" rel=\"noopener\">adsbdb</a>; dati delle rotte di David Taylor (Edinburgh) e Jim Mason (Glasgow).": "<strong>Flight routes</strong>: <a href=\"https://www.adsbdb.com\" target=\"_blank\" rel=\"noopener\">adsbdb</a>; route data by David Taylor (Edinburgh) and Jim Mason (Glasgow).",
  "<strong>Navi e traghetti</strong>: <a href=\"https://aisstream.io\" target=\"_blank\" rel=\"noopener\">aisstream.io</a>, segnali AIS raccolti da una rete di ricevitori. Gratuito per uso non commerciale.": "<strong>Ships and ferries</strong>: <a href=\"https://aisstream.io\" target=\"_blank\" rel=\"noopener\">aisstream.io</a>, AIS signals collected by a network of receivers. Free for non-commercial use.",
  "<strong>Satelliti</strong>: orbite da <a href=\"https://celestrak.org\" target=\"_blank\" rel=\"noopener\">CelesTrak</a>, calcolate con <a href=\"https://github.com/shashwatak/satellite-js\" target=\"_blank\" rel=\"noopener\">satellite.js</a>.": "<strong>Satellites</strong>: orbits from <a href=\"https://celestrak.org\" target=\"_blank\" rel=\"noopener\">CelesTrak</a>, computed with <a href=\"https://github.com/shashwatak/satellite-js\" target=\"_blank\" rel=\"noopener\">satellite.js</a>.",
  "<strong>Immagini della Terra</strong>: <a href=\"https://s2maps.eu\" target=\"_blank\" rel=\"noopener\">Sentinel-2 cloudless</a> by EOX IT Services GmbH (contains modified Copernicus Sentinel data 2020). Uso non commerciale.": "<strong>Earth imagery</strong>: <a href=\"https://s2maps.eu\" target=\"_blank\" rel=\"noopener\">Sentinel-2 cloudless</a> by EOX IT Services GmbH (contains modified Copernicus Sentinel data 2020). Non-commercial use.",
  "<strong>Luci delle città di notte</strong>: NASA Black Marble, tramite <a href=\"https://earthdata.nasa.gov/gibs\" target=\"_blank\" rel=\"noopener\">NASA GIBS</a>. Immagine composita dai satelliti, non in diretta.": "<strong>City lights at night</strong>: NASA Black Marble, via <a href=\"https://earthdata.nasa.gov/gibs\" target=\"_blank\" rel=\"noopener\">NASA GIBS</a>. A satellite composite, not live.",
  "<strong>Rilievo</strong>: Terrain Tiles di Mapzen su AWS Open Data.": "<strong>Terrain</strong>: Mapzen Terrain Tiles on AWS Open Data.",
  "<strong>Meteo e ricerca luoghi</strong>: <a href=\"https://open-meteo.com\" target=\"_blank\" rel=\"noopener\">Open-Meteo</a> (CC BY 4.0).": "<strong>Weather and place search</strong>: <a href=\"https://open-meteo.com\" target=\"_blank\" rel=\"noopener\">Open-Meteo</a> (CC BY 4.0).",
  "<strong>Motore 3D</strong>: <a href=\"https://cesium.com/platform/cesiumjs/\" target=\"_blank\" rel=\"noopener\">CesiumJS</a> (Apache 2.0).": "<strong>3D engine</strong>: <a href=\"https://cesium.com/platform/cesiumjs/\" target=\"_blank\" rel=\"noopener\">CesiumJS</a> (Apache 2.0).",
  "Vista 3D del cielo e della Terra": "3D view of the sky and the Earth",
  "Cambia luogo": "Change place",
  "Cerca un volo": "Find a flight",
  "Chiudi scheda": "Close card",
  "Vista": "View",
  "Rumore di cabina": "Cabin sound",
  "Condividi questo finestrino": "Share this window seat",
  "Città o paese": "City or town",
  "FR1234, AZ1234, RYR4KX o EI-DYC": "FR1234, BA178, RYR4KX or EI-DYC"
});
